# -*- coding: utf-8 -*-
"""demo_module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNnpROG10ZvqbGQawYEJAgwgUNSZ83de

Creating a module that returns cube of a number, addition of two numbers and multiplication of two numbers
"""

#function to get cube of a number
def cube(num):
  return num*num*num

#function to get summation of two numbers
def sum(a,b):
  return a+b

#function to get multiplication of two numbers
def mul(a,b):
  return a*b

